// react-client/src/app/dashboard/page.tsx
'use client';

import React from 'react';
import Link from 'next/link';
import { useAuth } from '../../context/AuthContext';
import {
  Kanban,
  Zap,
  TrendingUp,
  CheckCircle2,
  Clock,
  ArrowRight,
  Server,
  Sparkles,
  Bot,
  Activity,
  Users,
} from 'lucide-react';

export default function DashboardOverviewPage() {
  const { user } = useAuth();

  const metrics = [
    { title: 'Total Active Tasks', value: '142', change: '+12% this sprint', icon: Kanban, color: 'text-indigo-400', bg: 'bg-indigo-600/10 border-indigo-500/20' },
    { title: 'Active Sprints', value: '2', change: 'Sprint 42 & Sprint 43', icon: Zap, color: 'text-purple-400', bg: 'bg-purple-600/10 border-purple-500/20' },
    { title: 'Team Velocity', value: '88%', change: '42 / 48 Story Points', icon: TrendingUp, color: 'text-emerald-400', bg: 'bg-emerald-600/10 border-emerald-500/20' },
    { title: 'System Health', value: 'Online', change: 'Fastify & NestJS Active', icon: Activity, color: 'text-pink-400', bg: 'bg-pink-600/10 border-pink-500/20' },
  ];

  const recentActivities = [
    { id: 1, text: 'Fastify Auth Server rotated session refresh token', time: '10m ago', type: 'security' },
    { id: 2, text: 'NestJS Passport JWT Guard verified user credentials', time: '25m ago', type: 'auth' },
    { id: 3, text: 'Task AUTH-102 moved to In Progress by Techno Jerry', time: '1h ago', type: 'task' },
    { id: 4, text: 'Sprint 42 burndown updated (85% completion target)', time: '3h ago', type: 'sprint' },
  ];

  return (
    <div className="space-y-8 text-left">
      
      {/* Welcome Hero Banner */}
      <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-slate-800 relative overflow-hidden flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 flex items-center gap-1">
              <Sparkles className="w-3.5 h-3.5" /> Active Session
            </span>
            <span className="text-xs font-mono text-slate-400">Role: <strong className="text-white">{user.role}</strong></span>
          </div>
          <h1 className="text-2xl sm:text-4xl font-extrabold text-white tracking-tight">
            Welcome back, <span className="gradient-text">{user.firstName} {user.lastName}</span>!
          </h1>
          <p className="text-xs sm:text-sm text-slate-300 mt-2 max-w-xl">
            BoardPilot AI is connected to <strong>Fastify (Port 4000)</strong> & <strong>NestJS (Port 3000)</strong> backend engines.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <Link
            href="/dashboard/tasks"
            className="gradient-glow inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold text-xs shadow-lg shadow-indigo-600/20 hover:scale-105 transition-all"
          >
            <span>View Board</span>
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </div>

      {/* Metrics Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {metrics.map((m, idx) => {
          const IconComp = m.icon;
          return (
            <div key={idx} className="glass-card p-6 rounded-2xl border border-slate-800 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs text-slate-400 font-medium">{m.title}</span>
                <div className={`p-2.5 rounded-xl border ${m.bg}`}>
                  <IconComp className={`w-5 h-5 ${m.color}`} />
                </div>
              </div>
              <div className="text-3xl font-extrabold text-white">{m.value}</div>
              <span className="text-[11px] text-slate-400 block font-mono">{m.change}</span>
            </div>
          );
        })}
      </div>

      {/* Two Column Section: Sprint Progress & Recent Activity */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left 7 Cols: Sprint 42 Status */}
        <div className="lg:col-span-7 space-y-6">
          <div className="glass-panel p-6 rounded-3xl border border-slate-800">
            <div className="flex items-center justify-between mb-6">
              <div>
                <h3 className="text-base font-bold text-white">Sprint 42 — Progress Gauge</h3>
                <span className="text-xs text-slate-400">Target completion: Aug 25, 2026</span>
              </div>
              <span className="text-xs font-mono px-3 py-1 bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 rounded-full">
                87.5% Completed
              </span>
            </div>

            {/* Progress Bar */}
            <div className="w-full bg-slate-950 rounded-full h-3 p-0.5 border border-slate-800 mb-6">
              <div className="bg-gradient-to-r from-indigo-500 via-purple-500 to-emerald-400 h-full rounded-full w-[87.5%] transition-all duration-500" />
            </div>

            {/* Task Column Stats */}
            <div className="grid grid-cols-4 gap-3 text-center">
              <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
                <span className="text-xs text-slate-400 block">Backlog</span>
                <span className="text-lg font-bold text-white mt-1 block">12</span>
              </div>
              <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
                <span className="text-xs text-indigo-400 block">In Progress</span>
                <span className="text-lg font-bold text-indigo-300 mt-1 block">18</span>
              </div>
              <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
                <span className="text-xs text-purple-400 block">In Review</span>
                <span className="text-lg font-bold text-purple-300 mt-1 block">8</span>
              </div>
              <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
                <span className="text-xs text-emerald-400 block">Done</span>
                <span className="text-lg font-bold text-emerald-300 mt-1 block">42</span>
              </div>
            </div>
          </div>
        </div>

        {/* Right 5 Cols: Recent Activity Timeline */}
        <div className="lg:col-span-5">
          <div className="glass-panel p-6 rounded-3xl border border-slate-800">
            <h3 className="text-base font-bold text-white mb-4 flex items-center gap-2">
              <Activity className="w-4 h-4 text-indigo-400" /> Recent System Activity
            </h3>
            
            <div className="space-y-3">
              {recentActivities.map((act) => (
                <div key={act.id} className="p-3 bg-slate-950 rounded-xl border border-slate-800 flex items-start justify-between gap-3 text-xs">
                  <div>
                    <span className="text-slate-200 font-medium block">{act.text}</span>
                    <span className="text-[10px] text-slate-400 block mt-1">{act.time}</span>
                  </div>
                  <span className="w-2 h-2 rounded-full bg-indigo-500 shrink-0 mt-1" />
                </div>
              ))}
            </div>
          </div>
        </div>

      </div>

    </div>
  );
}

// vue-client/app/layouts/dashboard.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useAuth } from '~/composables/useAuth';
import {
  LayoutDashboard,
  Kanban,
  BarChart3,
  User,
  Settings,
  Users,
  LogOut,
  Bell,
  Search,
  ChevronLeft,
  ChevronRight,
  ShieldCheck,
  UserCheck
} from 'lucide-vue-next';

const route = useRoute();
const { user, setRole, logout } = useAuth();
const collapsed = ref(false);
const showNotifications = ref(false);

const isAdmin = computed(() => user.value.role === 'ORG_ADMIN');

const navItems = [
  { name: 'Overview', href: '/dashboard', icon: LayoutDashboard },
  { name: 'Tasks & Kanban', href: '/dashboard/tasks', icon: Kanban },
  { name: 'Sprint Reports', href: '/dashboard/reports', icon: BarChart3 },
  { name: 'User Profile', href: '/dashboard/profile', icon: User },
  { name: 'System Settings', href: '/dashboard/settings', icon: Settings },
  {
    name: 'User Management',
    href: '/dashboard/users',
    icon: Users,
    badge: 'Admin Only',
    adminOnly: true
  }
];

const isActive = (href: string) => {
  if (href === '/dashboard') return route.path === '/dashboard';
  return route.path.startsWith(href);
};
</script>

<template>
  <div className="flex h-screen bg-slate-950 text-slate-100 overflow-hidden">
    
    <!-- LEFT SIDEBAR NAVIGATION -->
    <aside
      :class="[
        collapsed ? 'w-20' : 'w-64',
        'transition-all duration-300 bg-slate-900/90 border-r border-slate-800 flex flex-col justify-between z-30 relative shrink-0'
      ]"
    >
      <div>
        <!-- Sidebar Header Logo -->
        <div className="h-16 flex items-center justify-between px-4 border-b border-slate-800">
          <NuxtLink to="/dashboard" className="flex items-center gap-3 overflow-hidden">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-indigo-600 via-purple-600 to-pink-500 p-0.5 shadow-md shrink-0">
              <div className="w-full h-full bg-slate-950 rounded-[10px] flex items-center justify-center">
                <LayoutDashboard className="w-4.5 h-4.5 text-indigo-400" />
              </div>
            </div>
            <span v-if="!collapsed" className="font-bold text-white tracking-tight text-base whitespace-nowrap">
              BoardPilot <span className="gradient-text">AI</span>
            </span>
          </NuxtLink>

          <button
            @click="collapsed = !collapsed"
            className="p-1.5 rounded-lg bg-slate-950 text-slate-400 hover:text-white border border-slate-800 transition-colors"
            aria-label="Toggle Sidebar"
          >
            <ChevronRight v-if="collapsed" className="w-4 h-4" />
            <ChevronLeft v-else className="w-4 h-4" />
          </button>
        </div>

        <!-- Nav Links -->
        <nav className="p-3 space-y-1.5">
          <NuxtLink
            v-for="item in navItems"
            :key="item.href"
            :to="item.href"
            :title="collapsed ? item.name : undefined"
            :class="[
              'flex items-center gap-3 px-3.5 py-3 rounded-xl text-xs font-semibold transition-all relative',
              isActive(item.href)
                ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-600/20'
                : 'text-slate-400 hover:text-white hover:bg-slate-800/60'
            ]"
          >
            <component :is="item.icon" :class="['w-4 h-4 shrink-0', isActive(item.href) ? 'text-white' : 'text-slate-400']" />
            
            <div v-if="!collapsed" className="flex items-center justify-between w-full">
              <span className="truncate">{{ item.name }}</span>
              <span
                v-if="item.badge"
                :class="[
                  'text-[9px] font-mono px-1.5 py-0.5 rounded border',
                  isAdmin
                    ? 'bg-purple-500/20 text-purple-300 border-purple-500/30'
                    : 'bg-amber-500/20 text-amber-300 border-amber-500/30'
                ]"
              >
                {{ item.badge }}
              </span>
            </div>

            <span v-if="collapsed && item.adminOnly" className="w-2 h-2 rounded-full bg-purple-400 absolute top-2 right-2" />
          </NuxtLink>
        </nav>
      </div>

      <!-- User Info Footer -->
      <div className="p-3 border-t border-slate-800 space-y-2">
        <div v-if="!collapsed" className="bg-slate-950/80 p-3 rounded-xl border border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2.5 overflow-hidden">
            <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-indigo-500 to-purple-600 font-bold text-white text-xs flex items-center justify-center shrink-0">
              {{ user.firstName[0] }}{{ user.lastName[0] }}
            </div>
            <div className="truncate">
              <span className="text-xs font-bold text-white block truncate">
                {{ user.firstName }} {{ user.lastName }}
              </span>
              <span className="text-[10px] font-mono text-indigo-400 block truncate">{{ user.role }}</span>
            </div>
          </div>
        </div>
        <div v-else className="flex justify-center">
          <div className="w-8 h-8 rounded-full bg-indigo-600 font-bold text-white text-xs flex items-center justify-center">
            {{ user.firstName[0] }}
          </div>
        </div>
      </div>
    </aside>

    <!-- MAIN CONTENT AREA -->
    <div className="flex-1 flex flex-col overflow-hidden">
      
      <!-- TOP HEADER -->
      <header className="h-16 bg-slate-900/60 border-b border-slate-800 px-4 sm:px-6 flex items-center justify-between shrink-0">
        
        <!-- Search -->
        <div className="flex items-center gap-4 flex-1 max-w-md">
          <div className="relative w-full">
            <input
              type="text"
              placeholder="Search tasks, sprints, members, or documents..."
              className="w-full pl-9 pr-4 py-2 rounded-xl bg-slate-950 border border-slate-800 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500"
            />
            <Search className="w-3.5 h-3.5 text-slate-500 absolute left-3 top-3" />
          </div>
        </div>

        <!-- Role Toggle & Actions -->
        <div className="flex items-center gap-4">
          
          <!-- Live RBAC Switcher -->
          <div className="hidden sm:flex items-center gap-2 bg-slate-950 p-1 rounded-xl border border-slate-800 text-xs">
            <span className="text-[10px] font-mono text-slate-400 pl-2 uppercase">Demo RBAC:</span>
            <button
              @click="setRole('ORG_ADMIN')"
              :class="[
                'px-3 py-1 rounded-lg text-xs font-semibold flex items-center gap-1 transition-all',
                isAdmin ? 'bg-purple-600 text-white shadow-md' : 'text-slate-400 hover:text-white'
              ]"
            >
              <ShieldCheck className="w-3.5 h-3.5" /> Admin Role
            </button>
            <button
              @click="setRole('TEAM_MEMBER')"
              :class="[
                'px-3 py-1 rounded-lg text-xs font-semibold flex items-center gap-1 transition-all',
                !isAdmin ? 'bg-indigo-600 text-white shadow-md' : 'text-slate-400 hover:text-white'
              ]"
            >
              <UserCheck className="w-3.5 h-3.5" /> User Role
            </button>
          </div>

          <!-- Notifications Button -->
          <div className="relative">
            <button
              @click="showNotifications = !showNotifications"
              className="p-2 rounded-xl bg-slate-950 text-slate-400 hover:text-white border border-slate-800 relative transition-colors"
              aria-label="Notifications"
            >
              <Bell className="w-4 h-4" />
              <span className="w-2 h-2 rounded-full bg-pink-500 absolute top-1.5 right-1.5 animate-ping" />
              <span className="w-2 h-2 rounded-full bg-pink-500 absolute top-1.5 right-1.5" />
            </button>

            <!-- Notifications Dropdown -->
            <div v-if="showNotifications" className="absolute right-0 mt-2 w-80 bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl p-4 z-50 text-left">
              <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                <span className="text-xs font-bold text-white">Notifications</span>
                <span className="text-[10px] font-mono bg-indigo-500/20 text-indigo-300 px-2 py-0.5 rounded">3 New</span>
              </div>
              <div className="space-y-3 pt-3">
                <div className="p-2.5 rounded-xl bg-slate-950 border border-slate-800/80">
                  <span className="text-xs font-semibold text-white block">New Task Assigned</span>
                  <span className="text-[11px] text-slate-400 block mt-0.5">AUTH-102 assigned by System Administrator.</span>
                </div>
                <div className="p-2.5 rounded-xl bg-slate-950 border border-slate-800/80">
                  <span className="text-xs font-semibold text-purple-300 block">Sprint 42 Started</span>
                  <span className="text-[11px] text-slate-400 block mt-0.5">Velocity target set to 45 story points.</span>
                </div>
              </div>
            </div>
          </div>

          <!-- Logout Button -->
          <button
            @click="logout"
            className="p-2 rounded-xl bg-slate-950 text-slate-400 hover:text-red-400 border border-slate-800 transition-colors"
            title="Sign Out"
          >
            <LogOut className="w-4 h-4" />
          </button>

        </div>

      </header>

      <!-- PAGE SLOT CONTENT -->
      <main className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8 bg-slate-950">
        <slot />
      </main>

    </div>
  </div>
</template>
